<a class="option"
    title="Buttons initialisation option"
    href="http://datatables.net/reference/option/buttons.buttons.action"
    target="_blank">
    <code>buttons.buttons.action<span>Option</span></code>
</a>
